name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # See https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions#pushing-package.json-changes-to-a-master-branch
          persist-credentials: false
      - name: Set as safe for following git commands
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Echo workspace
        run: echo "$GITHUB_WORKSPACE"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: https://registry.npmjs.org/
      - name: Install depenedencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --immutable
      - name: Lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint:ci
      - name: Test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 16
          # you can set branches for semantic-release above v16.
          branches: |
            [
              'main'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
